### ISSUE TITLE
Create the scenario to acquire Snivy

### ISSUE THREAD

**Issue by DoppelG3ngar** [DoppelG3ngar/Pokemon-Team-Rocket#1]
# Intro
 The intro scenario where the player can get a Snivy is as follows: 
1) Upon leaving the main characters home for the first time an event is triggered. 
2) Off screen a team rocket grunt can be heard reprimanding a Pokémon for being weak 
3) The rocket grunt then walks across screen, stopping to threaten the player. 
4) The player can interact with the Rocket grunt after the initial event and be reminded of the scenario. 
#### TODO: 
- [ ] Create a Team Rocket grunt that will be used in the script. 
	- This grunt will be persistent so the player can interact with them and be prompted about the scenario again. 
- [ ] Write dialog for the grunt to shout off screen and threaten the player. 
- [ ] Create the script for dialog + Rocket Grunt movement that will only be triggered once. 
- [ ] Tie this event to a map tile outside the main characters home. 
- [ ] Write dialog for the grunt when the player interacts with them after the initial event. 
# Puzzle Event
In the town there are several alleys where Snivy will be hiding. When the player approaches the Snivy, an event is triggered where the Snivy will scurry away to a different location. 

The player can use an Incense in the alley that will attract Snivy and lock their location. If the player has PokéFood in their inventory, they can interact with the Snivy to feed it. Snivy will then join the player's party. 

If the player does not have food in their inventory, the Snivy will lurch forward at the player pushing them away. 
#### TODO: 
- [ ] Create the PokéMart for the starter town 
	- [ ] Create an PokéMart NPC that sells typical corner store items
		- The NPC should have Incense and PokéFood available for purchase. 
	- [ ] Create an NPC that hints to the player how incense and PokéFood is calming 
- [ ] Create an NPC for Snivy
	- [ ] Create an event for Snivy when the player interacts with them and does not have PokéFood
		- The player interacts with them and Snivy lurches forward at the player, knocking them back 2 tiles. 
	- [ ] Create an event for Snivy when the player interacts with them and does have PokéFood. 
		- The player interacts with them and is prompted to feed Snivy.
			- Feeding Snivy will add Snivy to the player's party. 
			- Declining will end the dialog. 
- [ ] Create an event where Snivy will run away to the next preset location 
- [ ] Create an event for the player to use Incense to attract and lock in place Snivy
